### ISSUE TITLE
What would be the best way to inlcude a live wms (image) as my background / banner for my portal homepage?

### ISSUE THREAD

**Issue by jfrygeo** [Esri/ago-admin-wiki#10]
I tried to include a live wms in a web map and enable automatic updating in the webmap, however, the webmap on the homepage (following directions in the "Tweaking homepage" wiki) wasn't updating. It looks like it was cached in the portal html home page.

<i> example WMS tile server 
http://geoint.nrlssc.navy.mil/nrltileserver/wms?REQUEST=GetMap&VERSION=1.1.1&SERVICE=WMS&layers=BlueMarble24hr&bbox=-180,-90,180,90&format=image/png&width=2000&height=1000

**Comment by bmperkins** [comment]
Closing issue because we're retiring this wiki.
