### ISSUE TITLE
What modifications are required for these tools to work with Portal for ArcGIS?

### ISSUE THREAD

**Issue by RandySincoular** [Esri/ago-admin-wiki#11]

**Comment by ecaldwell** [comment]
Is there a particular tool you're interested in? Many of them will work for both ArcGIS Online and/or Portal. Usually, all that's needed is to supply the tool with the URL to your Portal.

**Comment by RandySincoular** [comment]
Hi Evan – thanks for getting back to me.  I was trying to get the “ago-tools” working with our Portal site.  I started by modifying the URL to point to our portal site but am running into an “unauthorized” error.  Let me know if there is any documentation on how to get this set of tools to work with our Portal.

ago-tools<https://github.com/Esri/ago-tools> - Python package to assist with administering ArcGIS Organizations. Sample tasks include:
·         Create a spreadsheet of all users
·         Update web map layer URLs
·         Find new users and add them to a list of groups
·         Move all items and transfer ownership and membership of groups between accounts, useful for transitioning to Enterprise logins


Thanks for your help.

Randy Sincoular
Alliant Energy

**Comment by ecaldwell** [comment]
Is your portal using enterprise authentication?

**Comment by RandySincoular** [comment]
Hi Evan – we are using integrated windows authentication in our portal.

Randy

**Comment by ecaldwell** [comment]
Unfortunately, ago-tools doesn't handle IWA (see [#43](https://github.com/Esri/ago-tools/issues/43)). You've got a couple alternatives. One, you should still have at least one single built-in user that you could sign in with. You could copy content to that account, then change the owner to an enterprise account. The other option is to check out [ArcREST](https://github.com/Esri/ArcREST), which has much better support for the various authentication types.
