### ISSUE TITLE
Firewall Issues using ago-tools

### ISSUE THREAD

**Issue by madamson001** [Esri/ago-admin-wiki#12]
I am trying to use examples on Github to administer ArcGIS Online, but due to our firewall access is denied.
Have tried code snippet on https://github.com/Esri/ago-admin-wiki/wiki/Set-up-your-machine-for-python-admin-scripting but get the following error:

IOError: [Errno socket error] [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

Is there a known workaround?

It appears there are known issues with the urllib libraries and firewall/permissions?. I have had a look at other Python libraries such as Requests but I am not sure if that would work or how to incorporate them in to ago tools. Quite new to Python so any advice would be gratefully received.

**Comment by ecaldwell** [comment]
Hi @madamson001, here are a couple of things to try. First, I recommend trying the [install procedure outlined in the ago-tools readme](https://github.com/Esri/ago-tools#installation). The instructions you followed in this wiki were written before I added the `setup.py` file to ago-tools. Second, if that doesn't work, try a vanilla python script like [this one](https://github.com/ecaldwell/portal-admin-examples/blob/develop/createCsvOfUsers.py). That will help rule out if it's an issue with ago-tools or specifically with your setup of python and/or firewall. My guess is that another library like Requests will not resolve the underlying problem if it is your firewall or network config.

**Comment by ecaldwell** [comment]
Were you able to troubleshoot this?

**Comment by bmperkins** [comment]
Closing issue because we're retiring this wiki.
