### ISSUE TITLE
ArcGIS Online Catalog Tool - 404 Error

### ISSUE THREAD

**Issue by joshuacroff** [Esri/ago-admin-wiki#13]
The link "ArcGIS Online Catalog Tool" returns a 404 Error when you attempt to navigate to the page. Looks like the tool is no longer available so should be removed from the list.

**Comment by jgravois** [comment]
thanks for the heads up!  i've updated the wiki but i left it in the list and just removed the link in case anyone has the wherewithal to spin it up themselves.
