### ISSUE TITLE
Vector tile link

### ISSUE THREAD

**Issue by gavinr** [Esri/ago-admin-wiki#14]
on [this wiki page](https://github.com/Esri/ago-admin-wiki/wiki/Tools), `http://maps.esri.com/AGSJS_Demos/templates/VectorBasemapStyleEditor/index.html` is a dead link - I believe the updated link is `https://maps.esri.com/jg/VectorBasemapStyleEditor/index.html`

**Comment by bmperkins** [comment]
Closing issue because we're retiring this wiki.
