### ISSUE TITLE
ArcGIS Online Resources

### ISSUE THREAD

**Issue by smpreston** [Esri/ago-admin-wiki#8]
Some of the courses listed on the Resources page are out of date or missing additional resources.

Configuring
Configuring and Administering an ArcGIS Online Subscription - this is now a web course titled Configuring and Administering an ArcGIS Online Organization (http://training.esri.com/gateway/index.cfm?fa=catalog.webCourseDetail&courseid=2738). 

Performing ArcGIS Online Administrator Tasks (http://training.esri.com/gateway/index.cfm?fa=catalog.webCourseDetail&courseid=2768) - this web course suggests different techniques to manage your ArcGIS Online organization, including management of usage, users, and content.

Publishing and sharing
Creating and Sharing GIS Content Using ArcGIS Online (http://training.esri.com/gateway/index.cfm?fa=catalog.webCourseDetail&courseid=2777) - this web course instructs students on different workflows to publish hosted web layers to ArcGIS Online.

Creating Web Applications Using Templates and Web AppBuilder for ArcGIS (http://training.esri.com/gateway/index.cfm?fa=catalog.webCourseDetail&courseid=2893) - this web course focuses on creating web applications using ArcGIS Online web application templates and Web AppBuilder for ArcGIS.

**Comment by oevans** [comment]
Thanks for the feedback! I removed the outdated listings and made the AGO training link more prominent/descriptive at the top of the page.
